### PR TITLE
114 tidy structure

### PR DESCRIPTION
**Pull request by jdha**

### CODE REVIEW

**Comment by jdha** [comment]
- [ ] Complete #104
- [ ] Split `env` in to machine dirs
- [ ] update setup script to reflect new `env` structure
- [ ] remove hardwired code to FORCING dirs - make machine specific

**Review by jasontempestholt — APPROVED** [review]
all fine

**Comment by jdha** [comment]
> all fine

I haven't finished - this is a draft PR ... 2 items left. Sorry I'm so slow :(

**Comment by jdha** [comment]
I've added `calc_tdiss` to the runscript options to allow you to toggle the new option on/off. 

Can @jasontempestholt or @chris-O-wilson see if this branch works as expected on Anemone. I've tested the MES setup on ARCHER2 and it sets up and runs.

- [ ] Setup and run works fine on Anemone

Once that's confirmed I'll merge to master

**Comment by jasontempestholt** [comment]
Ok, I'll have a go,
J.

**Comment by jasontempestholt** [comment]
Appear to be running fine on anemone with tdiss on.
Needed to add:
h_RMS_topog_anom.nc -> /home/jholt/SENEMO/INPUTS/h_rough_GEBCO2023_domcfg_GS1p2_full.nc

Previous experienced suggested 24 xios procs were need so I've changed to that.

Letting it run om.

J.

**Comment by jdha** [comment]
> Ok, I'll have a go, J.

Seems to be working for me. I've tested MES with `ln_calc_tdiss='.true.'` and `ln_calc_tdiss='.false.'` in the `runscript.slurm`

not sure whether this is all that's required to activate the new code ... (although I had to update the `namelist_cfg_template` as I'd forgotten to prepend the `h_RMS_topog_anom.nc` file with the `INPUTS` dir)

**Pull request merged**
