### PR TITLE
Core count correction for ZPS configs

### PR DESCRIPTION
**Pull request by jdha**

### CODE REVIEW

**Comment by jdha** [comment]
This update should address #105 ... the ZPS config has been run on archer2 using these new runscripts with updated node/core counts

**Review by katavouta — APPROVED** [review]
I have checked and I can run fine zps with the updates (I tested all your updated option for zps: 18, 29, 51, 67 and all of them work fine for me now)

**Comment by jdha** [comment]
@katavouta can you approve this ([hint](https://docs.github.com/en/enterprise-server@3.6/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews#))

**Review by katavouta — APPROVED** [review]
that works fine for me (tested the different choices for zps)

**Review by katavouta — APPROVED** [review]

**Review by katavouta — APPROVED** [review]

**Review by katavouta — APPROVED** [review]

**Pull request merged**
